default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: writeabout_development
  host: 127.0.0.1
  port: 5434
  username: writeabout_user

test:
  <<: *default
  database: writeabout_test
  host: 127.0.0.1
  port: 5434
  username: writeabout_user

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>