# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

prompts = 
  [
    "a blog post that you don't agree with",
    "a blog that is no longer active but you would like to see it return",
    "a blog that you read every day",
    "a book that a stranger has passed to you on the train",
    "a book that can only be read by one person",
    "a book that collects all your thoughts",
    "a book that differs in content depending on the reader",
    "a book that predicts the events for the next year",
    "a book that tells you everything that happens the following day",
    "a book that wields more power than any conventional weapon",
    "a book you recently read",
    "a book you would like to write",
    "a business that conflicts with your morals",
    "a castle that floats in the sky over looking a town",
    "a castle you know of and put a spin on its history",
    "a challenge you have overcome",
    "a change in your routine that has benefited you",
    "a child who invents their own perfect sibling",
    "a country that is in the news",
    "a delicate object",
    "a failed business and what to take from it",
    "a failed project",
    "a family on the frontier and their experience of surviving to spring",
    "a family tradition that you would like to revive",
    "a future in which your significant other is chosen for you",
    "a future where extinct species of animals have been replaced with robotic AI copies",
    "a future where the wealthy reside on lunar colonies while the rest remain on a crumbling society on Earth",
    "a game you recently played",
    "a gardener who uses mysterious methods to revive gardens",
    "a good deed you did this year",
    "a group of conspirators who's plan goes wrong",
    "a habit that you want to achieve this year",
    "a habit that you want to revive",
    "a habit you do every day",
    "a Halloween tradition you or your family do",
    "a hard decision you have made",
    "a journal that can re-write history",
    "a lone woman standing on the parapet of a castle",
    "a massive snowball fight that takes place every year between two towns",
    "a moment in life that treasure",
    "a movie you recently seen",
    "a music artist falling from fame",
    "a music tape that alters your perceptions for the better",
    "a musical instrument that has the power to hypnotise",
    "a new sport that you would like to see become more popular",
    "a new trend in task managers",
    "a new year party that never ends",
    "a news topic that is dividing opinion",
    "a place in the world that surprised you",
    "a place in the world that you frequently enjoy visiting",
    "a place in the world that you no longer recognise",
    "a place in the world you have yet to visit",
    "a place where it’s always spring",
    "a plot by thieves to steal a valuable item",
    "a plot to start a civil war",
    "a podcast you recently listened to",
    "a point in the year that you would have done different",
    "a political argument that differ on with another",
    "a product or service that you made, but it wasn't successful",
    "a product that you're going to give away for free",
    "a project that scared you",
    "a project that you're going to undertake without telling anyone",
    "a recent business trend ",
    "a recent news topic",
    "a recent technology trend",
    "a search for treasure where the treasure isn’t any kind of precious stone",
    "a secret that your siblings still don't know about",
    "a siege outside your own castle",
    "a skill you have learned in the last three months",
    "a snowman who won't melt",
    "a song that forces you to take certain actions when played",
    "a song that when sang is marked as a bad omen",
    "a sport that secretly love to watch",
    "a sport that you had misconceptions about, but now enjoy",
    "a sport that your kids play",
    "a sport you would like to take up",
    "a spring equinox that heralds that start of nature’s “fight back”",
    "a spy set in a fantasy world",
    "a spy set in a science fiction world",
    "a spy set in the victorian era",
    "a spy who is abandoned by his own country",
    "a spy who is brought back from retirement to help his country",
    "a spy who turns rogue on his country",
    "a spy who uses mind control as a weapon",
    "a startup that revives the memories of the deceased",
    "a stranger who mistakes you for someone else",
    "a stranger who you see every day but know nothing about them",
    "a stranger you have seen while commuting to work",
    "a successful business and what you take from it",
    "a task manager that you are new too",
    "a task manager that you love using",
    "a technology that you find intrusive or disruptive",
    "a technology that you take for granted",
    "a technology that you think is taken for granted or overlooked",
    "a time when a sibling was there for you in a time of need",
    "a tool that makes a real difference to how you work",
    "a topic in the news that is gaining attention",
    "a topic in the news that people are not paying attention to but should be",
    "a topic that will be in demand",
    "a topic that you disagree with",
    "a topic that you generalize in",
    "a topic that you plan on learning",
    "a topic that you see as a trending market",
    "a topic that you see as being phased out",
    "a topic that you specialise in",
    "a treasured item that you will pass on to someone else",
    "a tree that never sheds it’s leaves in the fall",
    "a tribal chant used to divide a settlement",
    "a typical Christmas day in the far future",
    "a warrior who uses a chant to enter berserk state",
    "a winter sport that you would like to play",
    "a world that is considering, but hesistant about visiting Earth",
    "a world where violent sports are a common means of entertaining",
    "a world without nationalities",
    "an abuse of power by a government or world leader",
    "an animal",
    "an app that is the core of your productivity",
    "an app that you don’t own, but would love to see made",
    "an app that you find difficult to use, but still use",
    "an app that you think should be free",
    "an app that you use daily",
    "an app that you would like to make",
    "an app that you would pay money for",
    "an author who influences your writing",
    "an idea you have had for a product",
    "an individuals plan to start a war",
    "an influential person in politics",
    "an issue in a sport that you enjoy",
    "an issue in your community",
    "an item that you want to buy but can't",
    "an item that you want to buy but isn't essential",
    "an item you want to buy",
    "an unusually prolonged winter that threatens spring and the following seasons",
    "any new opportunities that spring offers",
    "becoming a parent again",
    "becoming a parent for the first time",
    "being a hoarder",
    "being a leader",
    "being a saver",
    "being a spender",
    "being a team memeber",
    "being an extrovert",
    "being an introvert",
    "being cautious",
    "being certain",
    "being comfortable",
    "being confident",
    "being doubtful",
    "being fearless",
    "being happy",
    "being in the forest during fall",
    "being in the zone",
    "being minimalistic",
    "being negative",
    "being out of your depth",
    "being overcome",
    "being scared",
    "being the “product” of social media",
    "being tracked in a forest by a pack of wolves",
    "being withdrawn",
    "building a business from scratch",
    "changes in your daily habits and their benefits and drawbacks",
    "dealing with Internet trolls",
    "differences in opinion over a bill or law",
    "eight animals who take over from Santa's reindeer",
    "eSports and their impact on conventional sports",
    "every day being Christmas",
    "how beliefs are divided in your family and your country",
    "how castles might look and function if built today",
    "how global politics affects you",
    "how politics in your country can be improved",
    "how technology has improved your experience in the games you play",
    "how to create the perfect headline",
    "how to create the perfect landing page for a product or service",
    "how you finish a project",
    "how you have left and came back to your beliefs",
    "how you learn a particular topic",
    "how you make decisions",
    "how you manage your tasks with your task manager",
    "how you prefer to spend Christmas",
    "how you start a project",
    "how you stay motivated",
    "how you track your progress",
    "how you would build the next privacy friendly social media platform",
    "how you would like technology to be used in the world",
    "how you would prefer to celebrate your own Thanksgiving day",
    "how you would prefer to spend the holidays",
    "how you would revive interest in a topic or subject that many view as having had its day",
    "how your beliefs have made you who you are",
    "living without social media",
    "new trends in the business world",
    "non-goals for next year",
    "old man winter in the modern world",
    "one thing that makes Thanksgiving day special for you",
    "one thing you plan to do in spring",
    "positive",
    "positive and negative trends in gaming",
    "projects that you have enjoyed working on",
    "reviving one aspect of your life",
    "saying goodbye to someone",
    "saying hello to someone new",
    "shopping for a rare item",
    "someone you know who, is as close to you as a sibling would be",
    "something you are bad at",
    "something you are good at",
    "spring 100 years from now",
    "taking the next step to develop your business",
    "technology that you think the world is better without",
    "the action you can take right now to make a positive difference",
    "the advice you would give your child when they become a parent",
    "the appeal and influence of science fiction",
    "the benefits and drawbacks of indie microblogging",
    "the benefits and drawbacks of large shopping centres and malls",
    "the benefits and drawbacks of the converging paths of sports, technology and medicine",
    "the best accounts you follow on social media",
    "the best advice you have been given",
    "the best and worst games that you have played",
    "the best apps and tools that allow you to keep your data private and own your data as well",
    "the best place to be on the planet to experience spring",
    "the books you're reading this year",
    "the challenges you face as a parent and how you overcome these challenges",
    "the changing traditions of marriage and relationships",
    "the coldest day that you can remember",
    "the colours of fall",
    "the current state of the economy",
    "the differences between yourself and your online persona",
    "the drawbacks of your task manager",
    "the first time you voted",
    "the five apps you recommend for writing",
    "the five apps you use every day",
    "the future of internet privacy and the growing number of connected devices available",
    "the future of payments",
    "the future of shopping",
    "the future of social media",
    "the future of the Olympics and it’s feasibility of changing the host city every four years",
    "the idea of strangers on social media",
    "the ideal business you would like to run",
    "the importance of balance between the natural world and technology",
    "the importance of being able to start over",
    "the information you would be willing to share with organisations who would respect your privacy",
    "the issue of privacy and social media and what platforms can do about it",
    "the last time you left your comfort zone",
    "the negatives of parenting",
    "the next step in your career",
    "the night before Christmas",
    "the one gift you would like to receive",
    "the one place in the world that you would like to live",
    "the one place in the world you would love to visit now if you could",
    "the past year",
    "the perfect social media platform",
    "the person you would like to be",
    "the positives of parenting",
    "the problems with a social media platform",
    "the revival of non-digital methods and tools",
    "the roadmap for your next product or service",
    "the root of your worry",
    "the rules you set yourself",
    "the state of sport in the media and it’s future",
    "the tips you have for managing projects",
    "the tools you use to manage projects",
    "the ultimate to guide to learning about a specific topic",
    "the unfair working conditions of Santa's elves",
    "the value you get from social media",
    "the weather",
    "an app you use every day",
    "traditions that your family have on Thanksgiving",
    "two or more people locked in an elevator for six hours",
    "two people meeting for the first time",
    "two siblings separated at birth but re-united years later",
    "two strangers meeting for the first time",
    "waking up",
    "were you like to end up with your writing",
    "what being a gamer means to you",
    "what Christmas means to you",
    "what constitutes treasure in the age of technology",
    "what fall means to you",
    "what game you would to made",
    "what makes your significant other unique",
    "what motivates you",
    "what the future of gaming is",
    "what the holidays mean to you",
    "what you and your significant other agree on and disagree on",
    "what you are good at",
    "what you are thankful for",
    "what you dislike about Christmas",
    "what you have achieved in the last three months",
    "what you hope to achieve in spring",
    "what you hope to achieve in the next three months",
    "what you love about Christmas",
    "what you think the future will look like when it comes to technological advancements",
    "what you’re looking for in a significant other",
    "what your costume you choose for Halloween as a kid",
    "what your ideal Christmas away from home",
    "what your kids are going as for Halloween",
    "when procrastination is a good thing",
    "who is on your blog roll",
    "who you follow on Instagram",
    "who you follow on Twitter",
    "why you blog",
    "why you dislike Thanksgiving day",
    "why you may question your beliefs",
    "why your beliefs are important in your day to life",
    "you favourite memory of Halloween",
    "your beliefs",
    "your best advice for parenting",
    "your business and what step you will take next to grow it",
    "your Christmas day",
    "your decision making process",
    "your evening routine",
    "your experience of the first day of spring",
    "your favourite app",
    "your favourite blog",
    "your favourite book",
    "your favourite career quote",
    "your favourite character from a game",
    "your favourite collection of writers",
    "your favourite memory",
    "your favourite memory of Christmas ",
    "your favourite memory of fall",
    "your favourite memory of Thanksgiving day",
    "your favourite place in the world",
    "your favourite science fiction book",
    "your favourite science fiction character",
    "your favourite science fiction movie",
    "your favourite siblings from a book or movie",
    "your favourite social media celebrity",
    "your favourite social media platform",
    "your favourite sport",
    "your fears",
    "your first experience of building a product",
    "your first experience of sport",
    "your five favourite books",
    "your five favourite movies",
    "your five year plan",
    "your goal for the year",
    "your goals for next year",
    "your goto tool for everyday productivity",
    "your home as a castle",
    "your ideal home as a castle",
    "your ideal Thanksgiving day",
    "your ideal writing environment",
    "your ideal writing tools",
    "your lack of beliefs",
    "your least favourite sport",
    "your morning routine",
    "your most prized possession",
    "your most treasured time of the day",
    "your nationality and what it means to you",
    "your New Year resolution",
    "your personal manifesto",
    "your plan for the year",
    "your plans for the year",
    "your plans for this fall",
    "your political leaning",
    "your position in the local community",
    "your preferred digital task manager",
    "your preferred paper task manager",
    "your preferred style of writing",
    "your preparations for spring",
    "your preparations for winter",
    "your privacy concerns on social media",
    "your procrastination demons",
    "your product's first iteration and release",
    "your progress last week",
    "your progress over the last month",
    "your progress towards your goal for the year",
    "your significant other",
    "your three words for next year",
    "your three words for the year",
    "your views on traditional marriage"
  ]

prompts.each do |p|
  Prompt.create(prompt: p)
end